### PR TITLE
adds contrib sig for william-index

### PR DESCRIPTION
**Pull request by william-index**

### CODE REVIEW

**Comment by dacap** [comment]
Sorry @william-index, check if you can create a new commit that is related to your GitHub username (we've rollback the merge).

**Comment by william-index** [comment]
Reopened with a new date, let me know if Im doing something wrong. https://github.com/aseprite/opensource/pull/35

**Comment by william-index** [comment]
@dacap Also excited to get this in, because I just put up https://github.com/aseprite/Aseprite-Script-Examples/pull/1 today XD (see above for link to new sign PR)

**Comment by dacap** [comment]
Hi @william-index, sorry but both PRs are wrong 😢 You should:

1. Configure your name and email for the commit: https://help.github.com/articles/setting-your-commit-email-address-in-git/
2. Create one PR with just one commit.

At the moment you are using `Anderson <wanderson@LT-69745.local>` as your name/email for Git commits.

**Pull request merged**
